### ISSUE TITLE
[Info] Installation on Proxmox VE 8.0.4 as a VM

### ISSUE THREAD

**Issue by silycr** [IceWhaleTech/zimaos-rauc#5]
### [Info]

Notes for installation onto Proxmox VE 8.0.4 as a VM of the ZimaOS Beta as at v0.4.8.1

1.	Download latest ZimaOS  .img.xz file
	a.	Either download directly to Proxmox `/var/lib.vz/images` and unzip .xz
	b.	or like me, downloaded to PC, unzipped with 7zip and transferred ~4GB file with WinSCP. 
 2.	Create new VM in Proxmox. Other than the information below, the rest of the settings are your own to choose.
	- OS
	-> Select ‘Do not use any media’
	->Guest OS = Linux and 6.x – 2.6 Kernel
	- System
	-> BIOS = OVMF (UEFI)
	-> Add and select the EFI storage location
	-> SCSI Controller = VirtIO SCSI Single
	- Disk
	-> Choose an option here:
			Delete the default disk, and only the OS will be installed later
			Increment to scsi 1 and use disk as storage. OS will be on a separate disk later
3.	Mount image to VM Disk. Enter the Promox Server shell, either by ssh or GUI.
	- Confirming the file details. `$ qemu-img info /var/lib/vz/images/{FILENAME}.img`
	-> Replace `{FILENAME}`
	- Import the .img to the VM `$ qm set {VM_ID} –scsi0 {LOCAL_STORAGE}:0,import-from=/var/lib/vz/images/{FILENAME}.img`
	-> Replace `{VM_ID}` and `{FILENAME}`
	-> For example `$ qm set 999 –scsi0 local-zfs:0,import-from=/var/lib/vz/images/zimaos_zimacube-0.4.8.1.img`
4.	Adjust Boot Order
	- On the VM, select Options and change the boot order to scsi0
5.	Disable SecureBoot
	- As per, [https://www.youtube.com/watch?v=js_Xoa0f8zM](url)
	-> Select console, Start the VM and mash the esc key
	-> Device Manager >> Secure Boot Configuration >> Attempt Secure Boot >> Enter (to disable)
	-> Escape and exit

ZimaOS will now boot. It will not display the IP address in the console, so you’ll need to find that yourself or use the application linked in the original instructions.

**Comment by rucknapucknavitz** [comment]
Thanks for this! I did find that I needed a “double - before scsi” like so `$ qm set {VM_ID} --scsi0`

**Comment by silycr** [comment]
> Thanks for this! I did find that I needed a “double -“ before scsi like so `$ qm set {VM_ID} --scsi0`

Spot on, Thank you. Formatting in the comment changed -- to long -. I've just updated.

**Comment by Lauren-ED209** [comment]
Thank you very much for organizing this. May we repost your tutorial?

**Comment by silycr** [comment]
Yes, more than welcome

**Comment by Lauren-ED209** [comment]
Shared this tutorial in our forum - https://icewhale.community/t/zimaos-open-beta-install-on-pve-guide/349

**Comment by raller1028** [comment]
@silycr 
![img_v3_0255_46386026-741c-44e0-9572-587fac0635bg](https://github.com/IceWhaleTech/zimaos-rauc/assets/57336867/77477345-b564-4de8-bc41-419a61cc6d96)
We'll show more in version 0.4.9.1, what do you think of this display?

**Comment by silycr** [comment]
@raller1028 

Very useful. The WebGUI port would be handy as well.

Particularly for some of us that happen to forget which non-standard port we change it to last time we had to type the IP

**Comment by jerrykuku** [comment]
The default port 80 is hidden, but will be shown once other non-standard ports are used.

**Comment by KOPElan** [comment]
按照以上步骤，在创建用户的时候提示 Fail，无法创建用户。
![屏幕截图 2024-05-10 121204](https://github.com/IceWhaleTech/zimaos-rauc/assets/3346106/63abc1c4-0de8-4213-a448-8003f5f384a2)

**Comment by heliveth** [comment]
> 按照以上步骤，在创建用户的时候提示 Fail，无法创建用户。 ![屏幕截图 2024-05-10 121204](https://private-user-images.githubusercontent.com/3346106/329455135-63abc1c4-0de8-4213-a448-8003f5f384a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDczNjgsIm5iZiI6MTcxNjI0NzA2OCwicGF0aCI6Ii8zMzQ2MTA2LzMyOTQ1NTEzNS02M2FiYzFjNC0wZGU4LTQyMTMtYTQ0OC04MDAzZjVmMzg0YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMjMxNzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I4ZmM0MjdkZmQwNzMxZDNmOWIzZTY4MzczNzVkNjRjZjcyOTc3Yzc4NTM1MTk1MzA2ZTE1NzAxZWQ5ZTM3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uYV_ckQzbF9KNcitzxm7UIsf1wKleSIVbEtVDkfHqQo)

我也遇到同样的问题，无法创建用户，请问怎么解？

**Comment by steveof2620** [comment]
I have installed and running. When I go the webUI it asks me to create an account. Every time I try to create one it just says Fail.

**Comment by steveof2620** [comment]
Can anyone shed some light on to this? Why can't I create an account as prompted?
<img width="637" alt="Screenshot 2024-06-17 at 10 07 31" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/46661819/dcab9624-9df0-4810-9f10-8a013580cc7a">

**Comment by jarno9981** [comment]
> Can anyone shed some light on to this? Why can't I create an account as prompted?

its actually a os problem Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this error
/v2/users/events:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this error
/v2/zimaos/connect/status:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this error
/v1/users/refresh:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this error
index-6f2f0d83.js:3 Unauthorized, logging out ... null
Y @ index-6f2f0d83.js:3Understand this warning
index-6f2f0d83.js:3 Unauthorized, logging out ... Error: 401 Unauthorized
    at Y (index-6f2f0d83.js:3:13910)
    at index-6f2f0d83.js:3:14262
    at async Home-e82edb01.js:116:25095
Y @ index-6f2f0d83.js:3Understand this warning
Home-e82edb01.js:116 Error: 401 Unauthorized
    at Y (index-6f2f0d83.js:3:13910)
    at index-6f2f0d83.js:3:14262
    at async Home-e82edb01.js:116:25095
Home-e82edb01.js:16 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'createElement')
    at HTMLDocument.get [as createElement] (Home-e82edb01.js:16:33201)
    at st (Home-e82edb01.js:16:36044)
    at Home-e82edb01.js:23:12436Understand this error
/v1/users/register:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by megastary** [comment]
I also had the user registration Fail error mentioned by @jarno9981 and @steveof2620.
Resizing the imported disk fixed the issue. (I added 12GB, but you probably don't need that much)

**Comment by platini76** [comment]
any new guide on safe installation into proxmox?

**Comment by ragnardzz** [comment]
> I also had the user registration Fail error mentioned by @jarno9981 and @steveof2620. Resizing the imported disk fixed the issue. (I added 12GB, but you probably don't need that much)

thank you so much, it works 😊👌

**Comment by sedalex** [comment]
Hello! 
How do I install qemu guest agent in zimaos?

**Comment by R0GGER** [comment]
https://github.com/R0GGER/proxmox-zimaos

**Comment by sedalex** [comment]
> https://github.com/R0GGER/proxmox-zimaos

I understand that I need to install an agent for proxmox.
https://pve.proxmox.com/wiki/Qemu-guest-agent

**Comment by upsangel** [comment]
> > https://github.com/R0GGER/proxmox-zimaos
> 
> I understand that I need to install an agent for proxmox. https://pve.proxmox.com/wiki/Qemu-guest-agent

I have encountered the same question... I guess need to download the source and compile? Not even sure what distro Zima is built on...

**Comment by R3D347HR4Y** [comment]
You're a lifesaver
Some things I had to do in my case at stage 3:

`$ qemu-img info /var/lib/vz/template/iso/{FILENAME}.img`
instead of
`$ qemu-img info /var/lib/vz/images/{FILENAME}.img`
and
`$ qm set 100 --scsi0 local-lvm:0,import-from=/var/lib/vz/template/iso/{FILENAME}.img`
instead of 
`$ qm set {VM_ID} --scsi0 {LOCAL_STORAGE}:0,import-from=/var/lib/vz/images/{FILENAME}.img`

Thanks a lot @silycr

**Comment by SannyGrooves** [comment]
Just wanted to say: Big shoutout to Rogger for this automated installation script. Just run in Proxmox SSH (not VM) and installation wil go automatic with nice menu installation options.

Rogger automated script: https://github.com/R0GGER/proxmox-zimaos

**Comment by thehelmetedheinsight** [comment]
I just wrote the .img to a usb stick with Balena Etcher, but linux 'dd' will wotk as well. 

In Proxmox > Create VM, don't add media to the CD/DVD-rom device. ADD a USB device, plug in the USB stick that you imaged to (Etcher, dd).

Redirect Proxmox USB dev to that USB stick. Choose a UEFI BIOS, start the VM. During startup, press ESC to go into BIOS > set boot order - USB first. Proxmox shoud boot off the physical usb stick.

Install to your virtual HDD with the ZimaOS setup. I chose 64GB to play around with.

**Comment by kroese** [comment]
I created a Docker container of ZimaOS, it is similar to running it in Proxmox, but much easier to setup for newbies. 

It’s available to try now: [dockur/zima: ZimaOS inside a Docker container.](https://github.com/dockur/zima)

**Comment by arshadigital** [comment]
سشللذبسششش
